### PR TITLE
Add Authereum

### PR DESCRIPTION
**Pull request by miguelmota**
Adds [Authereum](https://authereum.org)

### CODE REVIEW

**Comment by miguelmota** [comment]
Fixes https://github.com/pelith/node-eauth-server/pull/4

The CDN url has been fixed 

@Gilg4mesh @SiriusTsou

**Comment by Gilg4mesh** [comment]
Please give me a referral code to register Authereum so I can try it out if we have new features in the future

**Comment by miguelmota** [comment]
@Gilg4mesh what's your telegram username?

**Comment by Gilg4mesh** [comment]
https://t.me/gilg4mesh

**Pull request merged**
